### ISSUE TITLE
Model not created if using CPU

### ISSUE THREAD

**Issue by gateway** [ThomasDougherty/pytorch-video-style-transfer#2]
Seems like my gpu doesn't have enough memory to run the training.  I have 2 of them but I'm not sure what the code is selecting to use.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   37C    P8     4W / 120W |    237MiB /  6078MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:02:00.0 Off |                  N/A |
| 21%   38C    P8     6W / 180W |      2MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2773      G   /usr/lib/xorg/Xorg                148MiB |
|    0   N/A  N/A      3784      G   ...mviewer/tv_bin/TeamViewer        8MiB |
|    0   N/A  N/A      6235      G   /usr/bin/gnome-shell               75MiB |
+-----------------------------------------------------------------------------+
```

command that fails

` python3 main.py train --dataset /home/gateway/work/video/pytorch-video-style-transfer/coco/train2014/ --style-image /home/gateway/work/styles/r.jpg  --save-model-dir /home/gateway/work/video/pytorch-video-style-transfer/models1/ --cuda 1`

```
  File "/home/gateway/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 7.93 GiB total capacity; 7.28 GiB already allocated; 56.38 MiB free; 76.79 MiB cached)
```

never the less I tried with cpu and it never creates the model or puts it in the model folder.. here is the output.

```
(base) gateway@gateway-media:~/work/video/pytorch-video-style-transfer$ python3 main.py train --dataset /home/gateway/work/video/pytorch-video-style-transfer/coco/train2014/ --style-image /home/gateway/work/styles/r.jpg  --save-model-dir /home/gateway/work/video/pytorch-video-style-transfer/models1/ --cuda 0
Starting train...
Epoch 0,0/27595. Total loss: 6.246087551116943. Loss distribution: feat 0.9998509883880615, style 0.0001274806709261611, tv 2.0540714103844948e-05, pop 9.633496347305481e-07
Killed
```

So my question is I would love to get the gpu working, I think its trying gpu 0 (which is my main display one) and my 1 is the 1080 which I usually use for AI and other work.. thoughts?

btw thanks for putting all this effort in... wanted to avoid using some older techniques and optical flow.. here is a video I did a year or so ago that took ages.. https://youtu.be/ktI3uTlqb8E and this https://youtu.be/72FIC0zJPMs but the audio is off for some reason and never took the time to fix it..

**Comment by gateway** [comment]
oh just fyi.. 

```
>>> torch.cuda.get_device_name(1)
'GeForce GTX 1060 6GB'
>>> ^[[A^C
KeyboardInterrupt
>>> torch.cuda.get_device_name(0)
'GeForce GTX 1080'
>>> 
```

**Comment by ThomasDougherty** [comment]
You can specify GPU with the enviormental variable:
CUDA_VISIBLE_DEVICES=1
Let me know if this helps.

**Comment by gateway** [comment]
Hmm, tried 0 and 1, still getting out of memory :/ 

```
(base) gateway@gateway-media:~/work/video/pytorch-video-style-transfer$ python3 main.py train --dataset /home/gateway/work/video/pytorch-video-style-transfer/coco/train2014/ --style-image /home/gateway/work/styles/r.jpg  --save-model-dir /home/gateway/work/video/pytorch-video-style-transfer/models1/ --cuda 1
Starting train...
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    main()
  File "main.py", line 84, in main
    train(args)
  File "/home/gateway/work/video/pytorch-video-style-transfer/engine.py", line 82, in train
    features_y = vgg(y)
  File "/home/gateway/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gateway/work/video/pytorch-video-style-transfer/models.py", line 35, in forward
    h = self.slice2(h)
  File "/home/gateway/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gateway/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/gateway/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gateway/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/gateway/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 7.93 GiB total capacity; 7.28 GiB already allocated; 56.38 MiB free; 76.79 MiB cached)
```

oh and the output of the last line still says GPU 0, so I cant seem to target 1, is their a small code change I can make or force it to 1.. guess I dont have enough memory.. grrr :/

**Comment by gateway** [comment]
Solved by decreasing the batch size.  I noticed you had various other arguments in your main file.. I'm curious how long this will take.. any pointers on converting the video.. use ffmpeg to dump to png's or?

**Comment by ThomasDougherty** [comment]
@gateway it takes a few hours for me. It's a little slow to train but fast for stylization on videos. Hoping to work on future implementations to speed up training. stylization is done on a directory with your images, so ffmpeg is good, or also cv2. I use moviepy for making videos with audio.
